development:
  adapter: postgresql
  encoding: unicode
  database: mngdr2_development
  pool: 5
  username: louy7
  password: password1

test:
  adapter: postgresql
  encoding: unicode
  database: mngdr2_test
  pool: 5
  username: louy7
  password: password1
default: &default
  adapter: postgresql
  encoding: unicode
  
